# Kernel logistic regression

In this notebook, we will use the formalization of logistic regression which assumes that y is 0,1 (which is the case for the challenge).

In [1]:
import sys
sys.path.append('D:/Documents/University/MVA/Kernel Methods/mva-KMML-challenge/KernelFlows')
sys.path.append('D:/Documents/University/MVA/Kernel Methods/mva-KMML-challenge/General')


import cvxpy as cp

import numpy as np

from matrix_operations import norm_matrix
import kernel_functions as kfunc
import matplotlib.pyplot as plt

In [2]:
# This is for opposite sign loss, ignoe in this case
def logistic_loss(weights,Y, K, reg = 1e-5):
    pred = K@weights
    n = pred.shape[0]
    norm = weights.T@(K@weights)
    return 1/n*np.sum(np.log(1+np.exp(-Y*pred)), axis = 0) + reg*norm
    
    

In [3]:
def logistic_loss(weights, Y, K, reg = 1e-5):
    norm =     norm = weights.T@(K@weights)
    n = weights.shape[0]

In [4]:
n = 10
X = np.random.random((n, 10))
Y = np.random.binomial(1, 0.5, size = n)

In [5]:
Y

array([0, 1, 1, 1, 1, 1, 0, 0, 1, 1])

In [6]:
mu = np.array([1.0])
K = kfunc.kernel_RBF(X, X ,mu)

In [18]:
weights = np.random.random(10)

In [19]:
logistic_loss(weights, Y, K)

Expression(CONSTANT, UNKNOWN, ())

In [20]:
logistic_loss(weights, Y, K, reg )

Expression(CONSTANT, UNKNOWN, ())

In [70]:
def logistic_loss(weights, Y, K, reg = 1e-5):
    norm = cp.quad_form(weights, K)
    norm = 0
    n = weights.shape[0]
    f_x = K@weights 
    
    return norm + cp.sum(cp.logistic(f_x) - cp.multiply(f_x, Y), axis = 0)/n
    

In [71]:
weights = cp.Variable(n)
reg = cp.Parameter()
K = cp.Parameter((n,n))
K = kfunc.kernel_RBF(X, X ,mu)
problem = cp.Problem(cp.Minimize(logistic_loss(weights, Y, K, reg)))

In [72]:
K = kfunc.kernel_RBF(X, X ,mu)
reg.value = 1e-5
problem.solve()

2.6415129875216777e-08

In [73]:
weights.value

array([ 22.63547686, -47.47791101,  22.6308437 ,  21.95710219,
        26.81951739, -61.03608078,  15.45996493,  35.35430806,
        21.30163491,   6.23124791])

In [62]:
problem = cp.Problem(cp.Minimize(weights.T@(K@weights) + cp.sum(cp.logistic(K@weights) - cp.multiply(K@weights , Y), axis = 0) ))

In [135]:
# Generate a random non-trivial quadratic program.
m = 15
n = 10
p = 5
np.random.seed(1)
P = np.random.randn(n, n)
P = P.T @ P
q = np.random.randn(n)
G = np.random.randn(m, n)
h = G @ np.random.randn(n)
A = np.random.randn(p, n)
b = np.random.randn(p)

# Define and solve the CVXPY problem.
x = cp.Variable(n)
prob = cp.Problem(cp.Minimize((1/2)*cp.quad_form(x, P) + q.T @ x),
                 [G @ x <= h,
                  A @ x == b])
prob.solve()

# Print result.
print("\nThe optimal value is", prob.value)
print("A solution x is")
print(x.value)
print("A dual solution corresponding to the inequality constraints is")
print(prob.constraints[0].dual_value)


The optimal value is 86.89141585569918
A solution x is
[-1.68244521  0.29769913 -2.38772183 -2.79986015  1.18270433 -0.20911897
 -4.50993526  3.76683701 -0.45770675 -3.78589638]
A dual solution corresponding to the inequality constraints is
[ 0.          0.          0.          0.          0.         10.45538054
  0.          0.          0.         39.67365045  0.          0.
  0.         20.79927156  6.54115873]


In [139]:
def logistic_loss(weights, Y, K, reg = 1e-5):
    norm = weights.T@(K@weights)
    n = weights.shape[0]
    f_x = K@weights 
    
    return norm + np.sum(np.log(1 + np.exp(f_x)) - np.multiply(f_x, Y), axis = 0)

In [142]:
mu = np.array([1.0])
K = kfunc.kernel_RBF(X, X ,mu)
weights = np.random.random(10)
logistic_loss(weights, Y, K)

19.99691459622227

In [137]:
from scipy.optimize import minimize

In [145]:
res = minimize(logistic_loss, weights, args = (Y, K), method='BFGS')

In [146]:
res.message

'Optimization terminated successfully.'

In [147]:
res.x

array([-0.24743654,  0.24201593, -0.27564949, -0.249895  ,  0.21668603,
       -0.25432756,  0.22590625,  0.20425867,  0.24492095,  0.20129036])